version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3011:3011"
    networks:
      - jssish-network

  backend:
    build: ./backend
    ports:
      - "3010:3010"
    networks:
      - jssish-network

networks:
 jssish-network: {}
